namespaces:
  wifi:
    commands:
      connect:
        command: nmcli d wifi connect '{{ network }}'
        description: Connect to a favourite wifi network.
        interactive: false
        tags:
          - network
        parameters:
          network:
            prompt: Choose a network
            exclusive: true
            choices: 'nmcli --colors no -g ssid d wifi list'
  nix:
    commands:
      rebuild:
        command: sudo nixos-rebuild {{ type }} --impure --flake .#
        description: Rebuild nix setup
        interactive: true
        tags:
          - sudo
        parameters:
          type:
            default: switch
            prompt: How to rebuild
            exclusive: true
            choices:
              - switch
              - reboot
      clean-generations:
        command: nix-collect-garbage --delete-older-than {{ days }}d
        description: Delete old nix generations
        interactive: true
        parameters:
          days:
            default: 30
            prompt: Number of days to keep
  bookmarks:
    commands:
      github:
        command: xdg-open "https://github.com/{{ user }}/{{ project }}"
        description: Open a GitHub project
        tags:
          - browser
        parameters:
          user:
            default: f4z3r
            prompt: Choose user
          project:
            prompt: Choose project
      nixos:
        command: xdg-open "https://search.nixos.org/packages?channel={{ channel }}"
        description: Open NixOS packages and versions
        tags:
          - browser
        parameters:
          channel:
            default: unstable
            prompt: Choose channel
            choices:
              - unstable
              - "23.11"
  git:
    commands:
      prune-branckes:
        command: git fetch -p && git for-each-ref --format '%(refname:short) %(upstream:track)' | awk '$2 == "[gone]" { print $1 }' | xargs -r git branch -D
        description: Removes all local branches that no longer track an upstream. Run after pruning the remote.
        interactive: true
        tags:
          - local
          - clean
  docker:
    commands:
      prune-containers:
        command: docker container list -a | perl -lane 'print @F[0] if ($_ =~ /Exited/ and $_ !~ /k3d/)' | xargs -r docker rm
        description: Delete all exited containers
        interactive: true
        tags:
          - local
          - clean
      prune-images:
        command: docker images | tail -n+2 | perl -lane 'print @F[2] if @F[1] =~ /<none>/' | xargs -r docker rmi
        description: Delete all container images missing a tag
        interactive: true
        tags:
          - local
          - clean
  dependent:
    commands:
      dependent-choices:
        command: echo -n "Separator is {{ sep }} and chosen values is {{ value }}"
        description: Test
        interactive: true
        parameters:
          sep:
            prompt: Choose Separator
            choices:
              - ":"
              - "|"
          value:
            prompt: Choose value
            choices: echo -n 'this:that|other|yes:no' | tr "{{ sep }}" "\n"
config:
  shell: zsh
  picker: fzf
  pickers:
    fzf:
      default_options: "--layout=reverse --inline-info --ansi"
